local packman = require('nvim.plugins.packman.packman')

packman.get('neoclide/coc.nvim')
packman.get('norcalli/nvim-colorizer.lua')
packman.get('kyazdani42/nvim-web-devicons')
packman.get('junegunn/fzf.vim')
packman.get('tomtom/tcomment_vim')
packman.get('nvim-treesitter/nvim-treesitter')
packman.get('justinmk/vim-sneak')
packman.get('junegunn/vim-easy-align')
packman.get('tpope/vim-surround')
packman.get('tpope/vim-fugitive')
packman.get('tpope/vim-repeat')
packman.get('liuchengxu/vim-which-key')
packman.get('SirVer/ultisnips')
packman.get('alexluigit/xvimux')
